"""Generate the Tofu font from Adobe NotDef's .notdef glyph."""

from io import BytesIO
from pathlib import Path

from fontTools.fontBuilder import FontBuilder
from fontTools.pens.ttGlyphPen import TTGlyphPen
from fontTools.ttLib import TTFont


ROOT = Path(__file__).resolve().parent
SOURCE_FILE = ROOT / "adobe-notdef" / "AND-Regular.ttf"
OUTPUT_FILE = ROOT / "dist" / "Tofu.ttf"

FONT_NAME = "Tofu"
STYLE_NAME = "Regular"
POSTSCRIPT_NAME = "Tofu-Regular"

# OpenType LONGDATETIME uses 1904-01-01 as its epoch. 2082844800 represents
# 1970-01-01 and keeps generated bytes independent of the wall clock.
FONT_TIMESTAMP = 2_082_844_800


def _load_source_font() -> TTFont:
    if not SOURCE_FILE.is_file():
        raise FileNotFoundError(
            f"Adobe NotDef source font not found: {SOURCE_FILE}. Initialize the adobe-notdef git submodule before generating Tofu."
        )
    return TTFont(SOURCE_FILE, recalcTimestamp=False, lazy=False)


def _copy_notdef(source: TTFont):
    glyph_set = source.getGlyphSet()
    if ".notdef" not in glyph_set:
        raise ValueError("Adobe NotDef source has no .notdef glyph")

    pen = TTGlyphPen(None)
    glyph_set[".notdef"].draw(pen)
    return pen.glyph()


def build_font() -> bytes:
    """Build Tofu and return its deterministic TrueType bytes."""
    source = _load_source_font()
    try:
        units_per_em = source["head"].unitsPerEm
        advance_width, left_side_bearing = source["hmtx"][".notdef"]
        glyph = _copy_notdef(source)
    finally:
        source.close()

    builder = FontBuilder(units_per_em, isTTF=True)
    builder.font["head"].created = FONT_TIMESTAMP
    builder.font["head"].modified = FONT_TIMESTAMP

    builder.setupGlyphOrder([".notdef"])
    # Tofu is selected explicitly as nuv's final fallback. An empty cmap makes
    # every character resolve to GID 0 while keeping maxp.numGlyphs exactly 1.
    builder.setupCharacterMap({})
    builder.setupGlyf({".notdef": glyph})
    builder.setupHorizontalMetrics(
        {".notdef": (advance_width, left_side_bearing)}
    )
    builder.setupHorizontalHeader(ascent=880, descent=-120, lineGap=0)
    builder.setupNameTable(
        {
            "familyName": FONT_NAME,
            "styleName": STYLE_NAME,
            "fullName": f"{FONT_NAME} {STYLE_NAME}",
            "psName": POSTSCRIPT_NAME,
        },
        windows=True,
        mac=False,
    )
    builder.setupOS2(
        version=4,
        xAvgCharWidth=advance_width,
        usWeightClass=400,
        usWidthClass=5,
        fsType=0,
        yStrikeoutSize=50,
        yStrikeoutPosition=220,
        achVendID="TOFU",
        fsSelection=0x0040,  # REGULAR
        usFirstCharIndex=0,
        usLastCharIndex=0,
        sTypoAscender=880,
        sTypoDescender=-120,
        sTypoLineGap=0,
        usWinAscent=880,
        usWinDescent=120,
        sxHeight=0,
        sCapHeight=0,
        usDefaultChar=0,
        usBreakChar=32,
        usMaxContext=0,
        ulUnicodeRange1=0,
        ulUnicodeRange2=0,
        ulUnicodeRange3=0,
        ulUnicodeRange4=0,
        ulCodePageRange1=0,
        ulCodePageRange2=0,
    )
    builder.setupPost(
        keepGlyphNames=False,
        italicAngle=0,
        underlinePosition=-125,
        underlineThickness=50,
        isFixedPitch=1,
    )

    output = BytesIO()
    builder.save(output)
    return output.getvalue()


def main() -> None:
    font = build_font()
    OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_FILE.write_bytes(font)
    print(f"Generated {OUTPUT_FILE.relative_to(ROOT)} ({len(font)} bytes)")


if __name__ == "__main__":
    main()
