"""Generate the Tofu fonts from Adobe NotDef and Last Resort glyphs."""

import struct
from io import BytesIO
from pathlib import Path

import unicodedata2
from fontTools.fontBuilder import FontBuilder
from fontTools.misc.transform import Transform
from fontTools.pens.transformPen import TransformPointPen
from fontTools.pens.ttGlyphPen import TTGlyphPen, TTGlyphPointPen
from fontTools.ttLib import TTFont
from fontTools.ttLib.tables.DefaultTable import DefaultTable
from fontTools.ufoLib.glifLib import readGlyphFromString

ROOT = Path(__file__).resolve().parent
SOURCE_FILE = ROOT / "adobe-notdef" / "AND-Regular.ttf"
MONO_SOURCE_FILE = ROOT / "last-resort-font" / "font.ufo" / "glyphs" / "_notdef.glif"
OUTPUT_FILE = ROOT / "dist" / "Tofu.ttf"
MONO_OUTPUT_FILE = ROOT / "dist" / "Tofu-Mono.ttf"

FONT_NAME = "Tofu"
MONO_FONT_NAME = "Tofu Mono"
STYLE_NAME = "Regular"
POSTSCRIPT_NAME = "Tofu-Regular"
MONO_POSTSCRIPT_NAME = "Tofu-Mono"

# OpenType LONGDATETIME uses 1904-01-01 as its epoch. 2082844800 represents
# 1970-01-01 and keeps generated bytes independent of the wall clock.
FONT_TIMESTAMP = 2_082_844_800

# Unicode 17.0 DerivedCoreProperties.txt. HarfBuzz normally replaces a
# default-ignorable character with the font's space glyph. Keeping these out
# of the cmap and providing a blank space glyph preserves that behavior.
DEFAULT_IGNORABLE_RANGES = (
    (0x00AD, 0x00AD),
    (0x034F, 0x034F),
    (0x061C, 0x061C),
    (0x115F, 0x1160),
    (0x17B4, 0x17B5),
    (0x180B, 0x180F),
    (0x200B, 0x200F),
    (0x202A, 0x202E),
    (0x2060, 0x206F),
    (0x3164, 0x3164),
    (0xFE00, 0xFE0F),
    (0xFEFF, 0xFEFF),
    (0xFFA0, 0xFFA0),
    (0xFFF0, 0xFFF8),
    (0x1BCA0, 0x1BCA3),
    (0x1D173, 0x1D17A),
    (0xE0000, 0xE0FFF),
)


def _load_source_font() -> TTFont:
    if not SOURCE_FILE.is_file():
        raise FileNotFoundError(
            f"Adobe NotDef source font not found: {SOURCE_FILE}. Initialize the git submodules before generating Tofu."
        )
    return TTFont(SOURCE_FILE, recalcTimestamp=False, lazy=False)


def _copy_notdef(source: TTFont):
    glyph_set = source.getGlyphSet()
    if ".notdef" not in glyph_set:
        raise ValueError("Adobe NotDef source has no .notdef glyph")

    pen = TTGlyphPen(None)
    glyph_set[".notdef"].draw(pen)
    return pen.glyph()


def _load_halfwidth_notdef(units_per_em: int):
    if not MONO_SOURCE_FILE.is_file():
        raise FileNotFoundError(
            f"Last Resort source glyph not found: {MONO_SOURCE_FILE}. Initialize the git submodules before generating Tofu Mono."
        )

    class GlyphMetadata:
        pass

    metadata = GlyphMetadata()
    pen = TTGlyphPointPen(None)
    # Last Resort is 2048 UPM. Its .notdef has a 1024-unit advance, so the
    # normalized glyph naturally occupies half of Tofu's 1000-unit em.
    transform_pen = TransformPointPen(pen, Transform().scale(units_per_em / 2048))
    readGlyphFromString(
        MONO_SOURCE_FILE.read_text(encoding="utf-8"),
        glyphObject=metadata,
        pointPen=transform_pen,
    )
    if metadata.width != 1024:
        raise ValueError(
            f"Unexpected Last Resort .notdef advance: {metadata.width} (expected 1024)"
        )
    return pen.glyph()


def _is_default_ignorable(codepoint: int) -> bool:
    return any(start <= codepoint <= end for start, end in DEFAULT_IGNORABLE_RANGES)


def _halfwidth_ranges() -> list[tuple[int, int, int]]:
    """Return format 13 groups for Unicode 17 halfwidth characters.

    East Asian Width H, Na, and N require the halfwidth tofu; W and F require
    the fullwidth GID 0. Ambiguous-width (A) characters are flexible: an A
    range is included only when it belongs to a contiguous component that
    contains a required-halfwidth character. This connects halfwidth ranges
    without creating groups for isolated A ranges and therefore minimizes the
    number of format 13 groups. Space maps to a blank halfwidth glyph so
    HarfBuzz can hide default ignorables without using a visible tofu outline.
    """
    if unicodedata2.unidata_version != "17.0.0":
        raise RuntimeError(
            f"Expected Unicode data 17.0.0, got {unicodedata2.unidata_version}"
        )

    groups = []
    start = None
    has_required_halfwidth = False
    for codepoint in range(0x110001):
        if codepoint == 0x110000:
            kind = "barrier"
        elif codepoint == 0x20:
            kind = "space"
        elif 0xD800 <= codepoint <= 0xDFFF or _is_default_ignorable(codepoint):
            kind = "barrier"
        else:
            width = unicodedata2.east_asian_width(chr(codepoint))
            if width in {"H", "Na", "N"}:
                kind = "required"
            elif width == "A":
                kind = "flexible"
            else:
                kind = "barrier"

        if kind in {"required", "flexible"}:
            if start is not None:
                has_required_halfwidth |= kind == "required"
                continue
            start = codepoint
            has_required_halfwidth = kind == "required"
            continue

        if start is not None and has_required_halfwidth:
            groups.append((start, codepoint - 1, 1))
        start = None
        has_required_halfwidth = False
        if kind == "space":
            groups.append((codepoint, codepoint, 2))
    return groups


def _format_13_cmap(groups: list[tuple[int, int, int]]) -> DefaultTable:
    subtable_length = 16 + 12 * len(groups)
    data = struct.pack(">HHHHI", 0, 1, 0, 6, 12)  # Unicode full repertoire
    data += struct.pack(">HHIII", 13, 0, subtable_length, 0, len(groups))
    data += b"".join(struct.pack(">III", *group) for group in groups)
    table = DefaultTable("cmap")
    table.data = data
    return table


def _setup_common_tables(
    builder: FontBuilder,
    family_name: str,
    postscript_name: str,
    x_avg_char_width: int,
    is_fixed_pitch: int,
) -> None:
    builder.setupHorizontalHeader(ascent=880, descent=-120, lineGap=0)
    builder.setupNameTable(
        {
            "familyName": family_name,
            "styleName": STYLE_NAME,
            "fullName": f"{family_name} {STYLE_NAME}",
            "psName": postscript_name,
        },
        windows=True,
        mac=False,
    )
    builder.setupOS2(
        version=4,
        xAvgCharWidth=x_avg_char_width,
        usWeightClass=400,
        usWidthClass=5,
        fsType=0,
        yStrikeoutSize=50,
        yStrikeoutPosition=220,
        achVendID="TOFU",
        fsSelection=0x0040,  # REGULAR
        usFirstCharIndex=0,
        usLastCharIndex=0,
        sTypoAscender=880,
        sTypoDescender=-120,
        sTypoLineGap=0,
        usWinAscent=880,
        usWinDescent=120,
        sxHeight=0,
        sCapHeight=0,
        usDefaultChar=0,
        usBreakChar=32,
        usMaxContext=0,
        ulUnicodeRange1=0,
        ulUnicodeRange2=0,
        ulUnicodeRange3=0,
        ulUnicodeRange4=0,
        ulCodePageRange1=0,
        ulCodePageRange2=0,
    )
    builder.setupPost(
        keepGlyphNames=False,
        italicAngle=0,
        underlinePosition=-125,
        underlineThickness=50,
        isFixedPitch=is_fixed_pitch,
    )


def _new_builder(units_per_em: int) -> FontBuilder:
    builder = FontBuilder(units_per_em, isTTF=True)
    builder.font["head"].created = FONT_TIMESTAMP
    builder.font["head"].modified = FONT_TIMESTAMP
    return builder


def _save(builder: FontBuilder) -> bytes:
    output = BytesIO()
    builder.save(output)
    return output.getvalue()


def build_font() -> bytes:
    """Build Tofu and return its deterministic TrueType bytes."""
    source = _load_source_font()
    try:
        units_per_em = source["head"].unitsPerEm
        advance_width, left_side_bearing = source["hmtx"][".notdef"]
        glyph = _copy_notdef(source)
    finally:
        source.close()

    builder = _new_builder(units_per_em)
    builder.setupGlyphOrder([".notdef"])
    # Tofu is selected explicitly as nuv's final fallback. An empty cmap makes
    # every character resolve to GID 0 while keeping maxp.numGlyphs exactly 1.
    builder.setupCharacterMap({})
    builder.setupGlyf({".notdef": glyph})
    builder.setupHorizontalMetrics({".notdef": (advance_width, left_side_bearing)})
    _setup_common_tables(builder, FONT_NAME, POSTSCRIPT_NAME, advance_width, 1)
    return _save(builder)


def build_mono_font() -> bytes:
    """Build Tofu Mono with fullwidth and halfwidth tofu outlines."""
    source = _load_source_font()
    try:
        units_per_em = source["head"].unitsPerEm
        fullwidth_glyph = _copy_notdef(source)
    finally:
        source.close()

    halfwidth_glyph = _load_halfwidth_notdef(units_per_em)
    blank_pen = TTGlyphPen(None)

    builder = _new_builder(units_per_em)
    builder.font["head"].flags |= 1 << 14  # Last Resort font
    builder.setupGlyphOrder([".notdef", "tofu.half", "space"])
    builder.setupGlyf(
        {
            ".notdef": fullwidth_glyph,
            "tofu.half": halfwidth_glyph,
            "space": blank_pen.glyph(),
        }
    )
    builder.setupHorizontalMetrics(
        {
            ".notdef": (1000, 100),
            "tofu.half": (500, 63),
            "space": (500, 0),
        }
    )
    builder.font["cmap"] = _format_13_cmap(_halfwidth_ranges())
    _setup_common_tables(builder, MONO_FONT_NAME, MONO_POSTSCRIPT_NAME, 500, 0)
    return _save(builder)


def main() -> None:
    fonts = (
        (OUTPUT_FILE, build_font()),
        (MONO_OUTPUT_FILE, build_mono_font()),
    )
    OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    for path, font in fonts:
        path.write_bytes(font)
        print(f"Generated {path.relative_to(ROOT)} ({len(font)} bytes)")


if __name__ == "__main__":
    main()
